//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcmodelfirstproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisan
    {
        public int calisanNo { get; set; }
        public string adsoyad { get; set; }
        public string adres { get; set; }
        public string calisanTel { get; set; }
        public int departmanNo { get; set; }
    
        public virtual departman departman { get; set; }
    }
}
