//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcmodelfirstproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public departman()
        {
            this.calisan = new HashSet<calisan>();
        }
    
        public int departmanNo { get; set; }
        public string departmanAdi { get; set; }
        public string departmanAdres { get; set; }
        public string departmanTel { get; set; }
        public int firmaNo { get; set; }
    
        public virtual firma firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calisan> calisan { get; set; }
    }
}
