//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcmodelfirstproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firma()
        {
            this.departman = new HashSet<departman>();
        }
    
        public int firmaNo { get; set; }
        public string firmaAdi { get; set; }
        public string firmaAdres { get; set; }
        public string firmaTelefon { get; set; }
        public int plazaNo { get; set; }
    
        public virtual plaza plaza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<departman> departman { get; set; }
    }
}
